spring:
  redis:
    host: 172.29.0.236
    port: 6381
    database: 3
    timeout: 4000
    password: huwoRadis
    jedis:
      pool:
        max-wait: -1
        max-active: -1
        max-idle: 20
        min-idle: 10

  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        master:
          url: jdbc:mysql://192.168.202.102:3306/callme?useSSL=false&autoReconnect=true&characterEncoding=utf-8
          username: root
          password: Mysql@123
          driver-class-name: com.mysql.cj.jdbc.Driver # 3.2.0开始支持SPI可省略此配置
        slave_1:
          url: jdbc:mysql://pe-mirror.hds.huwo.tech:3306/callme?useSSL=false&autoReconnect=true
          username: upstream
          password: 2dMce5zYuUM5
          driver-class-name: com.mysql.cj.jdbc.Driver

